# Deployement
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: headless-svc-demo
    project: roboshop
spec:
  replicas: 4
  selector:
    matchLabels:
      purpose: headless-svc-demo
      project: roboshop
  template:
    metadata:
      labels:
        purpose: headless-svc-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
