apiVersion: v1
kind: Pod
metadata:
  name: annotation
  annotations:
    jenkins.url: https://jenkins.joindevops.com
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
