apiVersion: v1 
kind: Pod
metadata:
  name: resources-demo
  labels:
    project: roboshop
    component: resources
    environment: development
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:  
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
