apiVersion: v1 
kind: Service
metadata:
  name: service-np
spec:
  type: NodePort
  selector:
    project: roboshop
    component: service
    environment: dev
    purpose: nodeport 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
