apiVersion: v1 
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: service
    environment: dev
    purpose: loadbalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80