apiVersion: v1 
kind: Pod
metadata: 
  name: lmalinux
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
   - name: almalinux
     image: almalinux:9
     command: ["sleep","1000"]